baseURL = 'https://kcmagicpixel.com/'
enableGitInfo = true
enableRobotsTXT = true
languageCode = 'en-us'
summaryLength = 30
title = 'Magic Pixel'

[params]
subtitle = 'Kansas City Fighting Game Community Events'

[permalinks]
events = '/:section/:year/:month/:slug'

[frontmatter]
date = ['date', 'start_date']

[taxonomies]
event-series = 'series'
games = 'games'
